<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Legal Further Review</name>
   <tag></tag>
   <elementGuidId>15eb7200-9abd-42b4-9b03-9bd5000c6bb7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>second-level-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Bits/BPHADMIN/MISCELLANEOUS/SPU_LEGAL_INVST_MGMT.ASPX</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Legal Further Review</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_list&quot;)/li[@class=&quot;nav-item&quot;]/div[@class=&quot;sub-nav&quot;]/div[1]/div[@class=&quot;sub-nav-box&quot;]/ul[@class=&quot;second-level-nav&quot;]/li[@class=&quot;nav-item-child&quot;]/a[@class=&quot;second-level-link&quot;]</value>
   </webElementProperties>
</WebElementEntity>
