<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00BodyuiTabSVPReviewuiTab1uiTab1SvpOffenseAnalystScreen</name>
   <tag></tag>
   <elementGuidId>864dbb7d-cd03-43a8-aeb7-e7d63aa4ae5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_Body_uiTabSVPReview_uiTab1_uiTab1SvpOffense_uiRbTabSvpYes&quot;)[count(. | //input[@name = 'ctl00$Body$uiTabSVPReview$uiTab1$uiTab1SvpOffense$AnalystScreen' and @id = 'ctl00_Body_uiTabSVPReview_uiTab1_uiTab1SvpOffense_uiRbTabSvpYes' and @type = 'radio' and @value = 'uiRbTabSvpYes']) = count(//input[@name = 'ctl00$Body$uiTabSVPReview$uiTab1$uiTab1SvpOffense$AnalystScreen' and @id = 'ctl00_Body_uiTabSVPReview_uiTab1_uiTab1SvpOffense_uiRbTabSvpYes' and @type = 'radio' and @value = 'uiRbTabSvpYes'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$Body$uiTabSVPReview$uiTab1$uiTab1SvpOffense$AnalystScreen</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_uiTabSVPReview_uiTab1_uiTab1SvpOffense_uiRbTabSvpYes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$Body$uiTabSVPReview$uiTab1$uiTab1SvpOffense$uiRbTabSvpYes\',\'\')', 0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>uiRbTabSvpYes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_uiTabSVPReview_uiTab1_uiTab1SvpOffense_uiRbTabSvpYes&quot;)</value>
   </webElementProperties>
</WebElementEntity>
