<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table</name>
   <tag></tag>
   <elementGuidId>4dd11e71-0ab5-42f5-aa68-9c70ac2898be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_Body_uiDecisionType&quot;)/fieldset[1]/div[1][count(. | //*[@id = 'id(&quot;ctl00_Body_uiDecisionType&quot;)']) = count(//*[@id = 'id(&quot;ctl00_Body_uiDecisionType&quot;)'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_uiDecisionType&quot;)/fieldset[1]/div[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_uiDecisionType&quot;)</value>
   </webElementProperties>
</WebElementEntity>
