<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_tableCellStyleCountDR</name>
   <tag></tag>
   <elementGuidId>21c2ddce-e4f1-4095-8734-2ef64915eee2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_Body_FirstGrid&quot;)/table[@class=&quot;tableStyleDR&quot;]/tbody[1]/tr[@class=&quot;tableCellStyleDR&quot;]/td[@class=&quot;tableCellStyleCountDR&quot;][count(. | //*[@class = 'tableCellStyleCountDR']) = count(//*[@class = 'tableCellStyleCountDR'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellStyleCountDR</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_FirstGrid&quot;)/table[@class=&quot;tableStyleDR&quot;]/tbody[1]/tr[@class=&quot;tableCellStyleDR&quot;]/td[@class=&quot;tableCellStyleCountDR&quot;]</value>
   </webElementProperties>
</WebElementEntity>
