<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Totalcell</name>
   <tag></tag>
   <elementGuidId>0e16935c-0278-42fb-8fe7-1cc5235dfbb0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>685</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_FirstGrid&quot;)/table[@class=&quot;tableStyleDR&quot;]/tbody[1]/tr[@class=&quot;tableCellStyleDR&quot;]/td[@class=&quot;tableCellStyleCountDR&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
