<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ctl00BodyuiIptTabsuiMainTabuiNationality</name>
   <tag></tag>
   <elementGuidId>1fb7f96a-bd02-4153-8cde-63e51e583598</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_Body_uiIptTabs_uiMainTab_uiNationality&quot;)[count(. | //select[@name = 'ctl00$Body$uiIptTabs$uiMainTab$uiNationality' and @class = 'size-150px' and @id = 'ctl00_Body_uiIptTabs_uiMainTab_uiNationality']) = count(//select[@name = 'ctl00$Body$uiIptTabs$uiMainTab$uiNationality' and @class = 'size-150px' and @id = 'ctl00_Body_uiIptTabs_uiMainTab_uiNationality'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$Body$uiIptTabs$uiMainTab$uiNationality</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>size-150px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_uiIptTabs_uiMainTab_uiNationality</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_uiIptTabs_uiMainTab_uiNationality&quot;)</value>
   </webElementProperties>
</WebElementEntity>
