<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ctl00BodyuiIptTabsuiMainTabuiDualNationality</name>
   <tag></tag>
   <elementGuidId>87768cd7-f09f-4b28-824c-bf36eb2a0192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_Body_uiIptTabs_uiMainTab_uiDualNationality&quot;)[count(. | //select[@name = 'ctl00$Body$uiIptTabs$uiMainTab$uiDualNationality' and @id = 'ctl00_Body_uiIptTabs_uiMainTab_uiDualNationality']) = count(//select[@name = 'ctl00$Body$uiIptTabs$uiMainTab$uiDualNationality' and @id = 'ctl00_Body_uiIptTabs_uiMainTab_uiDualNationality'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$Body$uiIptTabs$uiMainTab$uiDualNationality</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>size-150px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_uiIptTabs_uiMainTab_uiDualNationality</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_uiIptTabs_uiMainTab_uiDualNationality&quot;)</value>
   </webElementProperties>
</WebElementEntity>
