<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ctl00BodyuiIptTabsuiMainTabuiInstitution</name>
   <tag></tag>
   <elementGuidId>ac57abe4-61fa-476c-9b31-e12fe478ef0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_Body_uiIptTabs_uiMainTab_uiInstitution&quot;)[count(. | //select[@name = 'ctl00$Body$uiIptTabs$uiMainTab$uiInstitution' and @class = 'size-150px' and @id = 'ctl00_Body_uiIptTabs_uiMainTab_uiInstitution']) = count(//select[@name = 'ctl00$Body$uiIptTabs$uiMainTab$uiInstitution' and @class = 'size-150px' and @id = 'ctl00_Body_uiIptTabs_uiMainTab_uiInstitution'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$Body$uiIptTabs$uiMainTab$uiInstitution</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>size-150px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_uiIptTabs_uiMainTab_uiInstitution</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_uiIptTabs_uiMainTab_uiInstitution&quot;)</value>
   </webElementProperties>
</WebElementEntity>
