<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00BodyTabstpCDCRDSHEvalQuestion4bEvalCriteriaNo</name>
   <tag></tag>
   <elementGuidId>4327a7be-b3c1-4761-8125-1b3be25bc58a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$Body$Tabs$tpCDCRDSHEval$tcDSHFinalEval$tpDSHEval$MDOFinalDSHEvaluationCriteria$uiEvaluationCriteriaGrid$ctl06$rblEvalCriteriaYesNo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_Tabs_tpCDCRDSHEval_tcDSHFinalEval_tpDSHEval_MDOFinalDSHEvaluationCriteria_uiEvaluationCriteriaGrid_ctl06_rblEvalCriteriaYesNo_1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_Tabs_tpCDCRDSHEval_tcDSHFinalEval_tpDSHEval_MDOFinalDSHEvaluationCriteria_uiEvaluationCriteriaGrid_ctl06_rblEvalCriteriaYesNo_1&quot;)</value>
   </webElementProperties>
</WebElementEntity>
