<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00BodyTabstpCDCRDSHEvaltcPrelimFinalEvaltpPrelimEvalPrelimDSHEvaluation</name>
   <tag></tag>
   <elementGuidId>f6fa8fa4-ac41-4cbb-bdf6-bddf459ca0a9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$Body$Tabs$tpCDCRDSHEval$tcPrelimFinalEval$tpPrelimEval$PrelimDSHEvaluation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_Tabs_tpCDCRDSHEval_tcPrelimFinalEval_tpPrelimEval_rbPrelimDSHEvalRqrdYes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbPrelimDSHEvalRqrdYes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_Tabs_tpCDCRDSHEval_tcPrelimFinalEval_tpPrelimEval_rbPrelimDSHEvalRqrdYes&quot;)</value>
   </webElementProperties>
</WebElementEntity>
