<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FinalCDCREvaluationQuestion5Yes</name>
   <tag></tag>
   <elementGuidId>f52d097f-82f4-4438-8a94-333f5c981b08</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$Body$Tabs$tpCDCRDSHEval$tcPrelimFinalEval$tpFinalEval$mdoFinalCDCREvaluationCriteria$uiEvaluationCriteriaGrid$ctl07$rblEvalCriteriaYesNo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_Tabs_tpCDCRDSHEval_tcPrelimFinalEval_tpFinalEval_mdoFinalCDCREvaluationCriteria_uiEvaluationCriteriaGrid_ctl07_rblEvalCriteriaYesNo_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_Tabs_tpCDCRDSHEval_tcPrelimFinalEval_tpFinalEval_mdoFinalCDCREvaluationCriteria_uiEvaluationCriteriaGrid_ctl07_rblEvalCriteriaYesNo_0&quot;)</value>
   </webElementProperties>
</WebElementEntity>
