<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00BodyTabstpCDCRDSHEvaltcPrelimFinalEvaltpFinalEvaluiFinalCDCREvaluatorDate</name>
   <tag></tag>
   <elementGuidId>3616010c-01a5-4004-ab74-6561260be3d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_Body_Tabs_tpCDCRDSHEval_tcPrelimFinalEval_tpFinalEval_uiFinalCDCREvaluatorDate&quot;)[count(. | //*[@name = 'ctl00$Body$Tabs$tpCDCRDSHEval$tcPrelimFinalEval$tpFinalEval$uiFinalCDCREvaluatorDate' and @id = 'ctl00_Body_Tabs_tpCDCRDSHEval_tcPrelimFinalEval_tpFinalEval_uiFinalCDCREvaluatorDate']) = count(//*[@name = 'ctl00$Body$Tabs$tpCDCRDSHEval$tcPrelimFinalEval$tpFinalEval$uiFinalCDCREvaluatorDate' and @id = 'ctl00_Body_Tabs_tpCDCRDSHEval_tcPrelimFinalEval_tpFinalEval_uiFinalCDCREvaluatorDate'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$Body$Tabs$tpCDCRDSHEval$tcPrelimFinalEval$tpFinalEval$uiFinalCDCREvaluatorDate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>size-date MaskedEditFocus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_Tabs_tpCDCRDSHEval_tcPrelimFinalEval_tpFinalEval_uiFinalCDCREvaluatorDate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nospell</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_Tabs_tpCDCRDSHEval_tcPrelimFinalEval_tpFinalEval_uiFinalCDCREvaluatorDate&quot;)</value>
   </webElementProperties>
</WebElementEntity>
