<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00BodygvMDOPreScreeningctl02chkAssignStaff</name>
   <tag></tag>
   <elementGuidId>71c23c95-37c5-4e8e-8761-c24962616cf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_Body_gvMDOPreScreening_ctl02_chkAssignStaff&quot;)[count(. | //*[@name = 'ctl00$Body$gvMDOPreScreening$ctl02$chkAssignStaff' and @id = 'ctl00_Body_gvMDOPreScreening_ctl02_chkAssignStaff']) = count(//*[@name = 'ctl00$Body$gvMDOPreScreening$ctl02$chkAssignStaff' and @id = 'ctl00_Body_gvMDOPreScreening_ctl02_chkAssignStaff'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$Body$gvMDOPreScreening$ctl02$chkAssignStaff</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_gvMDOPreScreening_ctl02_chkAssignStaff</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_gvMDOPreScreening_ctl02_chkAssignStaff&quot;)</value>
   </webElementProperties>
</WebElementEntity>
