<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AccommodationsProvided</name>
   <tag></tag>
   <elementGuidId>2d827607-4600-43b6-bc0d-00e087422c68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_Body_uiDEC&quot;)[count(. | //a[@id = 'ctl00_Body_uiDEC' and @href = concat('javascript:__doPostBack(' , &quot;'&quot; , 'ctl00$Body$uiDEC' , &quot;'&quot; , ',' , &quot;'&quot; , '' , &quot;'&quot; , ')') and (text() = 'Accommodations Provided' or . = 'Accommodations Provided')]) = count(//a[@id = 'ctl00_Body_uiDEC' and @href = concat('javascript:__doPostBack(' , &quot;'&quot; , 'ctl00$Body$uiDEC' , &quot;'&quot; , ',' , &quot;'&quot; , '' , &quot;'&quot; , ')') and (text() = 'Accommodations Provided' or . = 'Accommodations Provided')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_uiDEC</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:newWin('/Bits/Jump.aspx?cdc_num=B39646&amp;inst=CMC&amp;event_type=SUB&amp;client_id=114802','BAR');return;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$Body$uiDEC','')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accommodations Provided</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_uiDEC&quot;)</value>
   </webElementProperties>
</WebElementEntity>
