<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00BodyuiTabSVPDetailsuiTab8uiReffDecisionRbt (1)</name>
   <tag></tag>
   <elementGuidId>263c6a6f-9a15-47da-8ee1-e078ed193a7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_Body_uiTabSVPDetails_uiTab8_uiReffDecisionRbt_0&quot;)[count(. | //*[@name = 'ctl00$Body$uiTabSVPDetails$uiTab8$uiReffDecisionRbt' and @id = 'ctl00_Body_uiTabSVPDetails_uiTab8_uiReffDecisionRbt_0' and @onclick = concat('javascript:setTimeout(' , &quot;'&quot; , '__doPostBack(\' , &quot;'&quot; , 'ctl00$Body$uiTabSVPDetails$uiTab8$uiReffDecisionRbt$0\' , &quot;'&quot; , ',\' , &quot;'&quot; , '\' , &quot;'&quot; , ')' , &quot;'&quot; , ', 0)') and @type = 'radio']) = count(//*[@name = 'ctl00$Body$uiTabSVPDetails$uiTab8$uiReffDecisionRbt' and @id = 'ctl00_Body_uiTabSVPDetails_uiTab8_uiReffDecisionRbt_0' and @onclick = concat('javascript:setTimeout(' , &quot;'&quot; , '__doPostBack(\' , &quot;'&quot; , 'ctl00$Body$uiTabSVPDetails$uiTab8$uiReffDecisionRbt$0\' , &quot;'&quot; , ',\' , &quot;'&quot; , '\' , &quot;'&quot; , ')' , &quot;'&quot; , ', 0)') and @type = 'radio'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$Body$uiTabSVPDetails$uiTab8$uiReffDecisionRbt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_uiTabSVPDetails_uiTab8_uiReffDecisionRbt_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$Body$uiTabSVPDetails$uiTab8$uiReffDecisionRbt$0\',\'\')', 0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_uiTabSVPDetails_uiTab8_uiReffDecisionRbt_0&quot;)</value>
   </webElementProperties>
</WebElementEntity>
