<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00BodyuiTabSVPDetailsuiTab5uiAdditionalRiskRptctl01uiChkFactorAddRisk</name>
   <tag></tag>
   <elementGuidId>46b819d0-972b-4faa-bacf-0f454438ac40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_Body_uiTabSVPDetails_uiTab5_uiAdditionalRiskRpt_ctl01_uiChkFactorAddRisk&quot;)[count(. | //*[@name = 'ctl00$Body$uiTabSVPDetails$uiTab5$uiAdditionalRiskRpt$ctl01$uiChkFactorAddRisk' and @id = 'ctl00_Body_uiTabSVPDetails_uiTab5_uiAdditionalRiskRpt_ctl01_uiChkFactorAddRisk' and @onclick = concat('javascript:setTimeout(' , &quot;'&quot; , '__doPostBack(\' , &quot;'&quot; , 'ctl00$Body$uiTabSVPDetails$uiTab5$uiAdditionalRiskRpt$ctl01$uiChkFactorAddRisk\' , &quot;'&quot; , ',\' , &quot;'&quot; , '\' , &quot;'&quot; , ')' , &quot;'&quot; , ', 0)') and @type = 'checkbox']) = count(//*[@name = 'ctl00$Body$uiTabSVPDetails$uiTab5$uiAdditionalRiskRpt$ctl01$uiChkFactorAddRisk' and @id = 'ctl00_Body_uiTabSVPDetails_uiTab5_uiAdditionalRiskRpt_ctl01_uiChkFactorAddRisk' and @onclick = concat('javascript:setTimeout(' , &quot;'&quot; , '__doPostBack(\' , &quot;'&quot; , 'ctl00$Body$uiTabSVPDetails$uiTab5$uiAdditionalRiskRpt$ctl01$uiChkFactorAddRisk\' , &quot;'&quot; , ',\' , &quot;'&quot; , '\' , &quot;'&quot; , ')' , &quot;'&quot; , ', 0)') and @type = 'checkbox'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$Body$uiTabSVPDetails$uiTab5$uiAdditionalRiskRpt$ctl01$uiChkFactorAddRisk</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_uiTabSVPDetails_uiTab5_uiAdditionalRiskRpt_ctl01_uiChkFactorAddRisk</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$Body$uiTabSVPDetails$uiTab5$uiAdditionalRiskRpt$ctl01$uiChkFactorAddRisk\',\'\')', 0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_uiTabSVPDetails_uiTab5_uiAdditionalRiskRpt_ctl01_uiChkFactorAddRisk&quot;)</value>
   </webElementProperties>
</WebElementEntity>
