<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00BodyuiTabSVPDetailsuiTab4uiProtectiveFactorRptctl01uiChkFactorProFactor</name>
   <tag></tag>
   <elementGuidId>a716481b-6515-4f25-926a-662127825f27</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$Body$uiTabSVPDetails$uiTab4$uiProtectiveFactorRpt$ctl01$uiChkFactorProFactor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_uiTabSVPDetails_uiTab4_uiProtectiveFactorRpt_ctl01_uiChkFactorProFactor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$Body$uiTabSVPDetails$uiTab4$uiProtectiveFactorRpt$ctl01$uiChkFactorProFactor\',\'\')', 0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_uiTabSVPDetails_uiTab4_uiProtectiveFactorRpt_ctl01_uiChkFactorProFactor&quot;)</value>
   </webElementProperties>
</WebElementEntity>
