<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00BodyuiTabSVPDetailsuiTab3uiDynamicRiskRptctl01uiChkFactor</name>
   <tag></tag>
   <elementGuidId>4d485af7-3722-49a3-9e3d-6ab884b35226</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_Body_uiTabSVPDetails_uiTab3_uiDynamicRiskRpt_ctl01_uiChkFactor&quot;)[count(. | //input[@name = 'ctl00$Body$uiTabSVPDetails$uiTab3$uiDynamicRiskRpt$ctl01$uiChkFactor' and @id = 'ctl00_Body_uiTabSVPDetails_uiTab3_uiDynamicRiskRpt_ctl01_uiChkFactor' and @type = 'checkbox']) = count(//input[@name = 'ctl00$Body$uiTabSVPDetails$uiTab3$uiDynamicRiskRpt$ctl01$uiChkFactor' and @id = 'ctl00_Body_uiTabSVPDetails_uiTab3_uiDynamicRiskRpt_ctl01_uiChkFactor' and @type = 'checkbox'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$Body$uiTabSVPDetails$uiTab3$uiDynamicRiskRpt$ctl01$uiChkFactor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_uiTabSVPDetails_uiTab3_uiDynamicRiskRpt_ctl01_uiChkFactor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$Body$uiTabSVPDetails$uiTab3$uiDynamicRiskRpt$ctl01$uiChkFactor\',\'\')', 0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_uiTabSVPDetails_uiTab3_uiDynamicRiskRpt_ctl01_uiChkFactor&quot;)</value>
   </webElementProperties>
</WebElementEntity>
