<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Supervisor</name>
   <tag></tag>
   <elementGuidId>99f79078-4057-4c5f-a5e7-d9dcfaec9d39</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayout</name>
      <type>Main</type>
      <value>row</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayoutalign</name>
      <type>Main</type>
      <value>space-between center</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c5-171</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-layout</name>
      <type>Main</type>
      <value>row</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-layout-align</name>
      <type>Main</type>
      <value>space-between center</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Supervisor </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/bits-root[1]/bits-layout[1]/mat-sidenav-container[@class=&quot;sidebar-container mat-drawer-container mat-sidenav-container mat-drawer-container-explicit-backdrop mat-drawer-transition mat-drawer-opened&quot;]/mat-sidenav[@class=&quot;bits-dark-theme mat-drawer mat-sidenav ng-tns-c3-0 ng-trigger ng-trigger-transform mat-drawer-over ng-star-inserted&quot;]/div[@class=&quot;mat-drawer-inner-container&quot;]/mat-nav-list[@class=&quot;mat-nav-list mat-list-base ng-star-inserted&quot;]/bits-menu-item[@class=&quot;ng-tns-c5-158 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c5-158 ng-star-inserted&quot;]/bits-menu-item[@class=&quot;ng-tns-c5-168 ng-tns-c5-158 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c5-168 ng-star-inserted&quot;]/bits-menu-item[@class=&quot;ng-tns-c5-171 ng-tns-c5-168 ng-star-inserted&quot;]/mat-list-item[@class=&quot;mat-list-item ng-tns-c5-171 ng-star-inserted&quot;]/div[@class=&quot;mat-list-item-content&quot;]/div[@class=&quot;mat-list-text&quot;]/a[@class=&quot;bitsMenuItem cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/span[@class=&quot;ng-tns-c5-171&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Executive Staff'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GO Staff'])[1]/preceding::span[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bits-menu-item[6]/div/bits-menu-item[2]/mat-list-item/div/div[2]/a/span/span</value>
   </webElementXpaths>
</WebElementEntity>
