<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CDCNumber</name>
   <tag></tag>
   <elementGuidId>eef97107-4311-4a25-9c3d-d1fd4b72bc91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;gvInmatePetitions&quot;)/tbody[1]/tr[2]/td[2]/a[@id=&quot;lnkCDCNum&quot;][count(. | //*[@id = 'lnkCDCNum' and @href = concat('javascript:__doPostBack(' , &quot;'&quot; , 'ctl00$Body$gvInmatePetitions$ctl02$lnkCDCNum' , &quot;'&quot; , ',' , &quot;'&quot; , '' , &quot;'&quot; , ')')]) = count(//*[@id = 'lnkCDCNum' and @href = concat('javascript:__doPostBack(' , &quot;'&quot; , 'ctl00$Body$gvInmatePetitions$ctl02$lnkCDCNum' , &quot;'&quot; , ',' , &quot;'&quot; , '' , &quot;'&quot; , ')')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lnkCDCNum</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$Body$gvInmatePetitions$ctl02$lnkCDCNum','')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AA3413</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvInmatePetitions&quot;)/tbody[1]/tr[2]/td[2]/a[@id=&quot;lnkCDCNum&quot;]</value>
   </webElementProperties>
</WebElementEntity>
