<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00BodyRiskAssessmentTabsuiTab4uiSignTab4</name>
   <tag></tag>
   <elementGuidId>e252e238-0ce4-4067-93ef-f119e4a0b27b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_Body_RiskAssessmentTabs_uiTab4_uiSignTab4&quot;)[count(. | //*[@name = 'ctl00$Body$RiskAssessmentTabs$uiTab4$uiSignTab4' and @id = 'ctl00_Body_RiskAssessmentTabs_uiTab4_uiSignTab4']) = count(//*[@name = 'ctl00$Body$RiskAssessmentTabs$uiTab4$uiSignTab4' and @id = 'ctl00_Body_RiskAssessmentTabs_uiTab4_uiSignTab4'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$Body$RiskAssessmentTabs$uiTab4$uiSignTab4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary size-default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_RiskAssessmentTabs_uiTab4_uiSignTab4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign &amp; Save</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_RiskAssessmentTabs_uiTab4_uiSignTab4&quot;)</value>
   </webElementProperties>
</WebElementEntity>
