<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00BodyTabstabHearingPaneluiNewPanelistChair</name>
   <tag></tag>
   <elementGuidId>34c6e805-f5b9-4979-ad62-75ecaa584d2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_Body_Tabs_tabHearingPanel_uiNewPanelistChair&quot;)[count(. | //*[@name = 'ctl00$Body$Tabs$tabHearingPanel$uiNewPanelistChair' and @id = 'ctl00_Body_Tabs_tabHearingPanel_uiNewPanelistChair']) = count(//*[@name = 'ctl00$Body$Tabs$tabHearingPanel$uiNewPanelistChair' and @id = 'ctl00_Body_Tabs_tabHearingPanel_uiNewPanelistChair'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$Body$Tabs$tabHearingPanel$uiNewPanelistChair</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Body_Tabs_tabHearingPanel_uiNewPanelistChair</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_Tabs_tabHearingPanel_uiNewPanelistChair&quot;)</value>
   </webElementProperties>
</WebElementEntity>
