<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Disapproved</name>
   <tag></tag>
   <elementGuidId>606fd9cf-8931-4df4-9675-870b1b09eddb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_Body_Tabs_DecisionTB_ActionAP_content_ActionAtPanel&quot;)/fieldset[1]/table[@class=&quot;table-nopadding&quot;]/tbody[1]/tr[2]/td[1]/label[1][count(. | //*[@for = 'ctl00_Body_Tabs_DecisionTB_ActionAP_content_ActionAtDenyRB']) = count(//*[@for = 'ctl00_Body_Tabs_DecisionTB_ActionAP_content_ActionAtDenyRB'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_Body_Tabs_DecisionTB_ActionAP_content_ActionAtDenyRB</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disapproved</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Body_Tabs_DecisionTB_ActionAP_content_ActionAtPanel&quot;)/fieldset[1]/table[@class=&quot;table-nopadding&quot;]/tbody[1]/tr[2]/td[1]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
