<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Panel</name>
   <tag></tag>
   <elementGuidId>6d4afb20-775d-46ad-b9cb-c78e4f10e629</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;__tab_ctl00_Body_Tabs_tabHearingPanel&quot;)/span[1][count(. | //span[(text() = 'Panel' or . = 'Panel')]) = count(//span[(text() = 'Panel' or . = 'Panel')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Panel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__tab_ctl00_Body_Tabs_tabHearingPanel&quot;)/span[1]</value>
   </webElementProperties>
</WebElementEntity>
